In [1]:
import numpy as np

data1=[0,1,2,3,4,5]
a1= np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [2]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [3]:
a1.dtype

dtype('int32')

In [4]:
a2.dtype

dtype('float64')

In [5]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [6]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a1=np.array([1,2])
a2=np.array([3,4])
a1+a2

array([4, 6])

In [8]:
a1*3

array([3, 6])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(12). (4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [15]:
b2 = np.arange(5)
b2.shape

(5,)

In [16]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0,np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.eye(3) #단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [24]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1= str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [25]:
str_a1.dtype

dtype('<U5')

In [26]:
#### 난수 배열 생성

np.random.rand(2,3)

array([[0.44141863, 0.63420612, 0.0069092 ],
       [0.73352267, 0.3686727 , 0.51850661]])

In [28]:
np.random.rand()

0.7027352800146264

In [29]:
np.random.rand(2,3,4)

array([[[0.34060351, 0.12544491, 0.44992738, 0.9893977 ],
        [0.49082727, 0.69015409, 0.21775362, 0.40154935],
        [0.88781188, 0.30030622, 0.54112471, 0.63640265]],

       [[0.14908568, 0.29149914, 0.88864046, 0.91351083],
        [0.41743131, 0.85275   , 0.9850531 , 0.16713653],
        [0.92489409, 0.14219798, 0.69016096, 0.66304891]]])

In [31]:
np.random.randint(10, size=(3,4))

array([[4, 1, 9, 3],
       [9, 4, 7, 1],
       [9, 1, 5, 7]])

In [32]:
np.random.randn(2,3,4)

array([[[ 0.29905951, -0.63626002, -0.40047129, -0.30818874],
        [-0.72255343,  0.57999864, -1.04088663,  0.20383975],
        [-0.78674461, -0.13293713,  0.3288029 ,  0.24121601]],

       [[ 0.7452116 ,  0.303639  , -0.40205565,  0.07558762],
        [-0.08438341,  0.58597466, -0.41564605, -0.53056836],
        [ 0.60142932,  0.01977933, -0.29627971,  0.66802267]]])

In [34]:
####배열의 연산
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr1+arr2

array([11, 22, 33, 44])

In [38]:
arr1-arr2

array([ 9, 18, 27, 36])

In [39]:
arr1*2

array([20, 40, 60, 80])

In [40]:
arr1*arr2

array([ 10,  40,  90, 160])

In [41]:
arr2**2

array([ 1,  4,  9, 16], dtype=int32)

In [42]:
arr1>20 #비교연산자 타입: bool

array([False, False,  True,  True])

In [43]:
(arr1>20).astype(int) #결과 값 판별

array([0, 0, 1, 1])

In [45]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [46]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [47]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [48]:
[arr3.min(), arr3.max()]

[0, 4]

In [49]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
for ar in arr:
    print(ar.mean())

1.5
5.5
9.5


In [51]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [52]:
arr4.cumsum() #누적합

array([ 1,  3,  6, 10], dtype=int32)

In [53]:
arr4.cumprod() #누적곱

array([ 1,  2,  6, 24], dtype=int32)

In [54]:
####행렬연산
#
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [55]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [56]:
A.dot(B) #행렬 곱

array([[0, 1],
       [6, 7]])

In [58]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [62]:
Xhidden = np.array([0.9, 0.3, 0.4, 0.2, 0.8, 0.2, 0.1, 0.5, 0.6]).reshape(3,3)
Xhidden

array([[0.9, 0.3, 0.4],
       [0.2, 0.8, 0.2],
       [0.1, 0.5, 0.6]])

In [63]:
Winput_hidden = np.array([0.9,0.1,0.8]).reshape(3,1)
Winput_hidden

array([[0.9],
       [0.1],
       [0.8]])

In [64]:
Xhidden.dot(Winput_hidden)

array([[1.16],
       [0.42],
       [0.62]])

In [66]:
####전치행렬
#
A = np.array([0,1,2,3]).reshape(2,2)
A

np.transpose(A)

array([[0, 2],
       [1, 3]])

In [68]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [72]:
e = np.random.rand(3,1)
e

array([[0.3297506 ],
       [0.54708547],
       [0.85598465]])

In [75]:
W = np.array([0.9, 0.3, 0.4, 0.2, 0.8, 0.2, 0.1, 0.5, 0.6]).reshape(3,3)
W

array([[0.9, 0.3, 0.4],
       [0.2, 0.8, 0.2],
       [0.1, 0.5, 0.6]])

In [77]:
W.transpose().dot(e)

array([[0.4917911 ],
       [0.96458588],
       [0.75490812]])

In [78]:
#### 배열 인덱싱
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [79]:
a1[0]

0

In [80]:
a1[4]

40

In [81]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [82]:
a1[[1,3,4]]

array([10, 30, 40])

In [83]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [84]:
a2[0,2]

30

In [85]:
a2[2,2] = 95

In [86]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [87]:
a2[1]

array([40, 50, 60])

In [88]:
a2[1] = np.array([45,55,65]) #동일 표현
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [90]:
a2[1]=[47,57,67] #동일 표현
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [91]:
a2[[0,2], [0,1]]

array([10, 80])

In [92]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [93]:
a[(a%2)==0]

array([2, 4, 6])

In [94]:
#### 배열 슬라이싱
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [96]:
b1[:3]

array([ 0, 10, 20])

In [97]:
b1[2:]

array([20, 30, 40, 50])

In [98]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [99]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [100]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [101]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [102]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [103]:
b2[1][0:2]

array([40, 50])

In [105]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [106]:
a = np.random.rand(5,11)
a

array([[0.25365013, 0.19550849, 0.86515431, 0.06830717, 0.04858856,
        0.8182314 , 0.65938459, 0.84709062, 0.96094078, 0.05700681,
        0.61657903],
       [0.49487137, 0.63932769, 0.50877723, 0.62574574, 0.1825252 ,
        0.8944201 , 0.46016126, 0.63527769, 0.24308969, 0.41458682,
        0.37902753],
       [0.16320237, 0.69903202, 0.84309989, 0.99354323, 0.73813216,
        0.4466091 , 0.89861959, 0.26812916, 0.58164829, 0.22826673,
        0.70570812],
       [0.23260541, 0.48733331, 0.71144569, 0.89437128, 0.85019377,
        0.4095215 , 0.2085257 , 0.38510465, 0.99592173, 0.85310375,
        0.28911432],
       [0.23601758, 0.51684533, 0.2791719 , 0.96733832, 0.59845893,
        0.99840288, 0.01079886, 0.23801914, 0.51165577, 0.99173713,
        0.3187911 ]])

In [113]:
answer_data = a[:,:1]
answer_data

array([[0.25365013],
       [0.49487137],
       [0.16320237],
       [0.23260541],
       [0.23601758]])

In [114]:
input_data = a[:,1:]
input_data 

array([[0.19550849, 0.86515431, 0.06830717, 0.04858856, 0.8182314 ,
        0.65938459, 0.84709062, 0.96094078, 0.05700681, 0.61657903],
       [0.63932769, 0.50877723, 0.62574574, 0.1825252 , 0.8944201 ,
        0.46016126, 0.63527769, 0.24308969, 0.41458682, 0.37902753],
       [0.69903202, 0.84309989, 0.99354323, 0.73813216, 0.4466091 ,
        0.89861959, 0.26812916, 0.58164829, 0.22826673, 0.70570812],
       [0.48733331, 0.71144569, 0.89437128, 0.85019377, 0.4095215 ,
        0.2085257 , 0.38510465, 0.99592173, 0.85310375, 0.28911432],
       [0.51684533, 0.2791719 , 0.96733832, 0.59845893, 0.99840288,
        0.01079886, 0.23801914, 0.51165577, 0.99173713, 0.3187911 ]])