In [2]:
from PIL import Image

In [23]:
#파일 읽기 및 저장
im = Image.open('C:/Users/Public/Pictures/Sample Pictures/Penguins.jpg')

print(im.size)

im.save('Penguins_test.jpg')

im.show(0)

(1024, 768)


In [7]:
from PIL import Image
import urllib.request as request

url = 'https://imgc.allpostersimages.com/img/print/posters/dlillc-baby-emperor-penguin_a-G-13448178-14258382.jpg'

res = request.urlopen(url)
im = Image.open(res)
im.show()
print(im.size)

(325, 488)


In [11]:
from PIL import Image

#색상 변경
im = Image.open('Penguins_test.jpg').convert("L")

im.show()

In [16]:
#Thumbnail 이미지
size = (64,64)
im.thumbnail(size)

im.save('Penguins-thumb.jpg')

In [15]:
#이미지 부분 잘라내기
im = Image.open('Penguins_test.jpg')
cropImage = im.crop((100,100,150,150)) # 좌,상,우,하
cropImage.save('Penguins_crop.jpg')

In [19]:
########## center crop
from PIL import Image

def center_crop(im):
    crop_size = min(im.size)
    
    left = (im.size[0] - crop_size)//2
    top = (im.size[1]-crop_size)//2
    right = (im.size[0]+crop_size)//2
    bottom = (im.size[1]+crop_size)//2
    
    return im.crop((left, top, right, bottom))


im = Image.open('Penguins_test.jpg')
cropImage = center_crop(im)
cropImage.save('Penguins_center_crop.jpg')

In [20]:
#이미지 회전 및 Resize
from PIL import Image

im = Image.open('Penguins_test.jpg')

img2 = im.resize((600,600))
img2.save('Penguins_600.jpg')

img3 = im.rotate(90)
img3.save ('Penguins_rotate.jpg')

In [21]:
#이미지 필터링
from PIL import Image, ImageFilter

im = Image.open('Penguins_test.jpg')
blurImage = im.filter(ImageFilter.BLUR)

blurImage.save('Penguins_blur.jpg')

In [29]:
#이미지 <-> numpy베열
import numpy as np
from PIL import Image

im = Image.open('Penguins_test.jpg')

# image -> numpy array
im2arr = np.array(im)
print(im2arr)

print()

#numpy array -> image
arr2im = Image.fromarray(im2arr)
print(arr2im)

[[[120 175 216]
  [117 172 213]
  [118 173 214]
  ...
  [ 86 161 201]
  [ 86 161 201]
  [ 85 160 200]]

 [[120 175 216]
  [117 172 213]
  [118 173 214]
  ...
  [ 87 162 202]
  [ 86 161 201]
  [ 86 161 201]]

 [[121 176 217]
  [118 173 214]
  [118 173 214]
  ...
  [ 87 162 202]
  [ 88 163 203]
  [ 88 163 203]]

 ...

 [[110 116 114]
  [112 118 116]
  [195 204 201]
  ...
  [117 137 138]
  [101 122 125]
  [ 88 112 114]]

 [[118 124 122]
  [ 97 103 101]
  [ 84  93  90]
  ...
  [112 133 136]
  [111 135 137]
  [ 94 118 120]]

 [[ 83  87  86]
  [112 118 116]
  [ 83  92  89]
  ...
  [109 130 133]
  [108 132 134]
  [ 73  99 100]]]

<PIL.Image.Image image mode=RGB size=1024x768 at 0x5CD4320>


In [31]:
# numpy to csv

a = np.asarray([[1,2,3], [4,5,6], [7,8,9]])

a.tofile('foo.csv', sep=',', format = '%10.5f')
np.savetxt('bar.csv', a, fmt = '%10.5f', delimiter=',')